Feature/gmail data
willarion/react-seed pull request #5
Opened 2021-07-14 10:54 UTC by willarion

get gmail messages array with messages' data, added function to proceed GoogleMes to new convenient object added layout with list of messages

2021-07-14 15:44 UTC, AnastasiaKozhemyachko requested changes

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/hooks/useMessages.ts
> +function useMessages(token: string): Array<any> {
don't use any

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/hooks/useAuthToken.ts
> +  return access;
use can write `return React.useContext(LoginContext).access;`

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/utils/getUsefulMessageFields.ts
> +  function filter(array: Header[], key: string) {
more readable will be` Array<Header>`

2021-07-15 08:16 UTC, bondarchukse commented on src/api/api.ts
> +  const { data } = await axios.get(
You should use axios `param` property to send query params. see https://github.com/axios/axios

2021-07-15 08:16 UTC, bondarchukse commented on src/api/api.ts
> +export { getMessagesList };
we are use `export const getMessagesList = ` syntax usually

2021-07-15 08:16 UTC, bondarchukse commented on src/components/Post/Post.tsx
> +function getProperDate(dateString: string): string {
define it as arrow function. Try to keep the same coding style for all parts of application.

2021-07-15 08:16 UTC, bondarchukse commented on src/components/Post/Post.tsx
> +  const date = new Date(dateString);
you should check is `dateString` empty string, and is `date` valid

2021-07-15 08:16 UTC, bondarchukse commented on src/components/PostsContainer/PostsContainer.tsx
> +  const messages = useMessages(token);
you can simplify this part of the code with using `useAuthToken();`  inside the `useMessages` hook!

2021-07-15 08:16 UTC, bondarchukse commented on src/components/PostsContainer/PostsContainer.tsx
> +    <section className="postsContainer" style={{ padding: '20px' }}>
try to use scss instead of inline styles!

2021-07-15 08:16 UTC, bondarchukse commented on src/hooks/useMessages.ts
> +  const [messages, setMessages] = React.useState<Array<MessageToRender>>([]);
`MessageToRender` name is little bit weird

2021-07-15 08:16 UTC, bondarchukse commented on src/hooks/useMessages.ts
> +    getMessagesList(token)
you will have this call on logout, for empty token!

2021-07-15 08:16 UTC, bondarchukse commented on src/utils/getUsefulMessageFields.ts
> +export function getUsefulMessageFields(item: GoogleMessage): MessageToRender {
try to refactor it with lodash functions
````
import { find } from 'lodash';

const titleHeader = find(item.payload.headers, { name: 'Subject' });
const title = titleHeader?.value;
````

2021-07-15 13:19 UTC, merged